apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2-ingress
  namespace: test-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: pomotodo-dev.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pomotodo-service
            port:
              number: 80