apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2-ingress
  namespace: test-app
  annotations:
spec:
  ingressClassName: traefik
  rules:
  # 외부 팀원용 도메인
  - host: pomotodo.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test2-service
            port:
              number: 80
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test2-service
            port:
              number: 80